kind: pipeline
type: docker
name: default

clone:
  depth: 1

steps:
  - name: compile
    image: techknowlogick/xgo:latest
    entrypoint:
      - /bin/sh -c
    commands:
      - cd ..
      - cp -r src /go/src/historian
      - /build.sh historian
      - ls /build
    when:
      event:
      - tag

  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files:
        - dist/*
      checksum:
        - md5
        - sha1
        - sha256
        - sha512
        - adler32
        - crc32
    when:
      event:
      - tag