kind: pipeline
type: docker
name: default

clone:
  depth: 1

steps:
  - name: compile
    image: techknowlogick/xgo:latest
    entrypoint:
      - /bin/sh -c
    commands:
      - apt-get update
      - apt-get install zip
      - cd ..
      - cp -r src /go/src/historian
      - /build.sh historian
      - ls /build
      - cd src
      - zip -j ${DRONE_REPO_NAME}_${DRONE_TAG}.zip /build/*
    when:
      event:
      - tag

  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files:
        - - ${DRONE_REPO_NAME}_${DRONE_TAG}.zip
      checksum:
        - md5
        - sha1
        - sha256
        - sha512
        - adler32
        - crc32
    when:
      event:
      - tag
