kind: pipeline
type: docker
name: default

clone:
  depth: 1

steps:
  - name: compile
    image: techknowlogick/xgo:latest
    entrypoint:
      - /bin/sh -c
    commands:
      - cd ..
      - cp -r src /go/src/historian
      - /build.sh historian
      - ls /build