kind: pipeline
type: docker
name: default

clone:
  depth: 1

steps:
  - name: compile
    image:
      name: techknowlogick/xgo:latest
      entrypoint: ["/bin/bash", "-c"]
    commands:
      - cd ..
      - /build.sh historian
      - ls /build